# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "uhci_hcd"
        "ehci_pci"
        "ahci"
        "vmw_pvscsi"
        "sd_mod"
        "sr_mod"
      ];
      kernelModules = [];
    };

    kernelModules = [];
    extraModulePackages = [];
  };

  #fileSystems."/" = {
  #  device = "/dev/disk/by-uuid/b0d32d20-807f-462e-b41f-84610bea7dd3";
  #  fsType = "ext4";
  #};

  #fileSystems."/boot" = {
  #  device = "/dev/disk/by-uuid/422D-774E";
  #  fsType = "vfat";
  #  options = [
  #    "fmask=0077"
  #    "dmask=0077"
  #  ];
  #};

  #swapDevices = [
  #  {device = "/dev/disk/by-uuid/f50c935b-5602-485d-b9a4-7ca7b50e8666";}
  #];

  disko.devices = {
    disk.disk1 = {
      device = lib.mkDefault "/dev/sda";
      type = "disk";
      content = {
        type = "gpt";
        partitions = {
          boot = {
            name = "boot";
            size = "1M";
            type = "EF02";
          };
          esp = {
            name = "ESP";
            size = "500M";
            type = "EF00";
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
            };
          };
          root = {
            name = "root";
            size = "100%";
            content = {
              type = "lvm_pv";
              vg = "pool";
            };
          };
        };
      };
    };
    lvm_vg = {
      pool = {
        type = "lvm_vg";
        lvs = {
          root = {
            size = "100%FREE";
            content = {
              type = "filesystem";
              format = "ext4";
              mountpoint = "/";
              mountOptions = [
                "defaults"
              ];
            };
          };
        };
      };
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
